# 点此回到[[JAVA（由此开始）]]
## 场景：在程序运行中可能会出现不正常的情况

## 很多时候bug会越修越多，bug是改不完的，得用异常机制解决

## 关键字有：try ， catch ， finally ， throw ， throws

## finally,在异常中指无论try中的代码是否异常，总会执行的
- 场景用于回收资源：
	- IO流关闭
	- 数据库连接关闭
- （finally中return不同的场景）在try语句返回前，先保留返回值，然后执行finally中的语句
	- 如果finally中有return，同时还修改了值，则将值覆盖并返回
	- 如果finally中没有return，也没有修改，则返回保留的值
	- 如果finally中没有return，但是有修改值
		- 若该返回类型为基本数据类型或字符串，则依然返回保留值
		- 若该返回值为引用类型，则将值覆盖并返回
- 以下特殊情况不会执行finally
	- 虚拟机退出：在try或catch块中调用了System.exit()方法来终止程序，那么finally块将不会执行
	- 死循环或无限等待，导致线程永久阻塞的操作
	- 电源关闭或操作系统崩溃，那么`finally`块将无法执行。这种情况超出了Java程序的控制范围
	- 守护线程死亡,如果`try`块在一个守护线程中运行，并且所有非守护线程都已经结束，Java虚拟机将会退出，不会等待守护线程完成，因此`finally`块可能不会执行

## 四种种异常方式：
### 捕获异常：try - catch,在使用时，catch()内要注意抛出异常的顺序，将子类异常放最前面，而  父类 Exception e  放至最后面

### 声明异常：关键字为：throws  ，一般在方法中使用，让该方法向外抛出异常信息，方便处理大量方法时使用，让上一级的try-catch解决

### 抛出异常： 关键字：throw ， 在方法内处理异常时直接  else{ throw new Exception("error") },该方法也需要先声明异常

### 自定义异常：
- 第一步   先创建个自定义异常类，然后继承父类Exception
- 第二部   自定义构造方法，可重载
- 第三步   和抛出异常差不多，new 自定义异常类名()    就可，声明异常和catch（）可以时父类Exception也可以是自定义异常类名

## Object类（后面是继承关系）
- Throwable类（所有异常类的父类）
	- Error类（系统层面的错误，如内存溢出等）
	- Exception（代码层面的错误）
		- Checked Exception（检查型异常），指编译时异常，必须捕获异常或声明异常，如文件未找到等
			- SQLException
			- ClassNotFoundException
		- Runtime Exception（运行时异常），指启动、运行时人为的可能异常，或者由于输入的参数值不同导致可能会或不会发生异常，但都应该尽量避免


## 常见的异常：
- java.lang.NullPointerException   空指针异常，，原因：调用未初始化的对象或是不存在的对象
- java.lang.ClassNotFoundException   找不到指定的类，，原因：类的名称和路径加载错误；通常是程序试图通过字符串来加载某个类时可能发生的异常
- java.lang.NumberFormatException   字符串转数字异常，，原因：字符型数据中包含非数字型字符
- java.lang.IndexOutOfBoundsExpections  数组角标越界异常，在操作数组对象时发生
- java.lang.IllegalArgumentException  方法传递参数错误
- java.lang.ClassCastException   数据类型转换错误